import { Badge } from '../../components/ui/Badge';
import { LoadingState } from '../../components/ui/States';
import type { AdminPayment } from '../../api/adminResources';
import { formatDateTime, formatMoney, paymentMethodLabel, paymentStatusLabel, paymentStatusTone } from './paymentUtils';
import { PaymentReviewActions } from './PaymentReviewActions';
export function PaymentDetailPanel({ payment, isLoading, isActionPending, onApprove, onReject }: { payment: AdminPayment | undefined; isLoading: boolean; isActionPending: boolean; onApprove: () => void; onReject: (reason: string) => void }) {
  if (isLoading) return <LoadingState label="Cargando detalle…" />; if (!payment) return <p className="text-sm text-slate-500">Selecciona un pago para revisar su detalle operativo.</p>;
  return <div className="space-y-5"><div><div className="flex items-center gap-2"><h3 className="text-lg font-bold text-slate-950">{payment.patient_name ?? 'Paciente sin nombre'}</h3><Badge tone={paymentStatusTone(payment.status)}>{paymentStatusLabel(payment.status)}</Badge></div><p className="text-sm text-slate-500">{payment.practitioner_service_name} · {payment.practitioner_name}</p></div><dl className="grid gap-3 text-sm md:grid-cols-2"><div><dt className="text-slate-500">Cita</dt><dd className="font-medium">{formatDateTime(payment.appointment_starts_at)}</dd></div><div><dt className="text-slate-500">Ubicación</dt><dd className="font-medium">{[payment.organization_name, payment.location_name, payment.room_name].filter(Boolean).join(' · ') || '—'}</dd></div><div><dt className="text-slate-500">Método</dt><dd className="font-medium">{paymentMethodLabel(payment.method)}</dd></div><div><dt className="text-slate-500">Monto</dt><dd className="font-medium">{formatMoney(payment.amount, payment.currency)}</dd></div><div><dt className="text-slate-500">Vence</dt><dd className="font-medium">{formatDateTime(payment.expires_at)}</dd></div><div><dt className="text-slate-500">Evidencia recibida</dt><dd className="font-medium">{formatDateTime(payment.evidence_received_at)}</dd></div><div><dt className="text-slate-500">Revisado</dt><dd className="font-medium">{formatDateTime(payment.reviewed_at)}</dd></div><div><dt className="text-slate-500">Última decisión</dt><dd className="font-medium">{payment.latest_review_decision ?? '—'}</dd></div></dl><PaymentReviewActions payment={payment} isPending={isActionPending} onApprove={onApprove} onReject={onReject} /><section><h4 className="mb-2 font-semibold">Evidencias</h4>{(payment.evidence ?? []).length === 0 ? <p className="text-sm text-slate-500">Sin evidencias asociadas.</p> : <ul className="space-y-2">{(payment.evidence ?? []).map((e) => <li key={e.id} className="rounded-xl bg-slate-50 p-3 text-sm"><strong>{e.original_filename ?? 'Evidencia sin archivo visible'}</strong><br />{formatDateTime(e.uploaded_at)} · {e.uploaded_channel ?? 'canal no indicado'}{e.notes ? <><br />{e.notes}</> : null}</li>)}</ul>}</section><section><h4 className="mb-2 font-semibold">Revisiones</h4>{(payment.reviews ?? []).length === 0 ? <p className="text-sm text-slate-500">Sin revisiones registradas.</p> : <ul className="space-y-2">{(payment.reviews ?? []).map((r) => <li key={r.id} className="rounded-xl bg-slate-50 p-3 text-sm"><strong>{r.decision === 'approved' ? 'Aprobado' : 'Rechazado'}</strong> · {formatDateTime(r.reviewed_at)}{r.notes ? <><br />{r.notes}</> : null}</li>)}</ul>}</section></div>;
}
