import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { PageHeader } from '../../components/layout/PageHeader';
import { SectionCard } from '../../components/ui/Card';
import { FieldWrapper, Input, Select } from '../../components/ui/Form';
import { EmptyState, ErrorState, LoadingState } from '../../components/ui/States';
import { adminPaymentsApi, adminResourcesApi, type AdminPayment, type PaymentFilters } from '../../api/adminResources';
import type { AdminTenant } from '../../config/tenant';
import { PaymentList } from './PaymentList';
import { PaymentDetailPanel } from './PaymentDetailPanel';
import { PAYMENT_METHOD_OPTIONS, PAYMENT_STATUS_OPTIONS, paymentStatusLabel } from './paymentUtils';

type FilterState = Required<Pick<PaymentFilters, 'organization_id' | 'status' | 'method' | 'date_from' | 'date_to' | 'patient'>>;
export function PaymentsPage({ tenant }: { tenant: AdminTenant }) {
  const [filters, setFilters] = useState<FilterState>({ organization_id: '', status: '', method: '', date_from: '', date_to: '', patient: '' });
  const [selected, setSelected] = useState<AdminPayment | null>(null); const qc = useQueryClient();
  const apiFilters = useMemo(() => Object.fromEntries(Object.entries(filters).filter(([, v]) => v)) as PaymentFilters, [filters]);
  const payments = useQuery({ queryKey: ['payments', tenant.id, apiFilters], queryFn: () => adminPaymentsApi.listPayments(tenant.id, apiFilters) });
  const organizations = useQuery({ queryKey: ['organizations', tenant.id], queryFn: () => adminResourcesApi.listOrganizations(tenant.id) });
  const detail = useQuery({ queryKey: ['payments', tenant.id, selected?.id, 'detail'], queryFn: () => adminPaymentsApi.getPayment(tenant.id, selected!.id), enabled: Boolean(selected?.id) });
  const invalidate = async () => { await qc.invalidateQueries({ queryKey: ['payments', tenant.id] }); };
  const approve = useMutation({ mutationFn: (payment: AdminPayment) => adminPaymentsApi.approvePayment(tenant.id, payment.id), onSuccess: async (data) => { setSelected(data); await invalidate(); } });
  const reject = useMutation({ mutationFn: ({ payment, reason }: { payment: AdminPayment; reason: string }) => adminPaymentsApi.rejectPayment(tenant.id, payment.id, reason), onSuccess: async (data) => { setSelected(data); await invalidate(); } });
  const rows = payments.data ?? []; const summary = { total: rows.length, review: rows.filter((p) => ['evidence_received', 'under_review'].includes(p.status) || (p.method === 'pay_on_site' && p.status === 'pending')).length, approved: rows.filter((p) => ['approved', 'simulated_approved'].includes(p.status)).length, rejected: rows.filter((p) => p.status === 'rejected').length, expired: rows.filter((p) => p.status === 'expired').length };
  const activeDetail = detail.data ?? selected ?? undefined;
  return <><PageHeader eyebrow="Fase 6B.11" title="Pagos" description="Consulta intentos de pago asociados a citas y registra revisión manual básica sin pasarelas, webhooks ni conciliación bancaria." />
    <SectionCard title="Filtros" description="La búsqueda usa nombres legibles; UUIDs y schema del tenant permanecen internos."><div className="grid gap-4 md:grid-cols-3 lg:grid-cols-6"><FieldWrapper label="Organización"><Select value={filters.organization_id} onChange={(e) => setFilters({ ...filters, organization_id: e.target.value })}><option value="">Todas</option>{(organizations.data ?? []).map((o) => <option key={o.id} value={o.id}>{o.name}</option>)}</Select></FieldWrapper><FieldWrapper label="Método"><Select value={filters.method} onChange={(e) => setFilters({ ...filters, method: e.target.value })}>{PAYMENT_METHOD_OPTIONS.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}</Select></FieldWrapper><FieldWrapper label="Estado"><Select value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })}>{PAYMENT_STATUS_OPTIONS.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}</Select></FieldWrapper><FieldWrapper label="Desde"><Input type="date" value={filters.date_from} onChange={(e) => setFilters({ ...filters, date_from: e.target.value })} /></FieldWrapper><FieldWrapper label="Hasta"><Input type="date" value={filters.date_to} onChange={(e) => setFilters({ ...filters, date_to: e.target.value })} /></FieldWrapper><FieldWrapper label="Paciente"><Input value={filters.patient} onChange={(e) => setFilters({ ...filters, patient: e.target.value })} placeholder="Nombre o documento" /></FieldWrapper></div></SectionCard>
    <div className="grid gap-4 md:grid-cols-5">{[['Total', summary.total], ['Pendientes de revisión', summary.review], ['Aprobados', summary.approved], ['Rechazados', summary.rejected], ['Vencidos', summary.expired]].map(([label, value]) => <SectionCard key={label} title={String(value)} description={String(label)}><span className="text-xs text-slate-500">{label === 'Pendientes de revisión' ? paymentStatusLabel('under_review') : 'Resumen operativo'}</span></SectionCard>)}</div>
    <div className="grid gap-6 xl:grid-cols-[1.4fr_1fr]"><SectionCard title="Listado de pagos" description="Intentos asociados a citas del tenant actual.">{payments.isLoading ? <LoadingState label="Cargando pagos…" /> : null}{payments.isError ? <ErrorState description={(payments.error as Error).message} /> : null}{payments.isSuccess && rows.length === 0 ? <EmptyState title="Sin pagos" description="No hay intentos con los filtros seleccionados." /> : null}{rows.length > 0 ? <PaymentList payments={rows} selectedId={selected?.id} onSelect={setSelected} /> : null}</SectionCard><SectionCard title="Detalle y revisión" description="La aprobación o rechazo solo actualiza pago y estado de pago de la cita; no confirma, cancela ni libera cupos.">{approve.isError ? <ErrorState description={(approve.error as Error).message} /> : null}{reject.isError ? <ErrorState description={(reject.error as Error).message} /> : null}<PaymentDetailPanel payment={activeDetail} isLoading={detail.isLoading} isActionPending={approve.isPending || reject.isPending} onApprove={() => activeDetail && approve.mutate(activeDetail)} onReject={(reason) => activeDetail && reject.mutate({ payment: activeDetail, reason })} /></SectionCard></div></>;
}
