import { useMemo, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { Button } from '../../components/ui/Button';
import { FieldWrapper, Input, Select } from '../../components/ui/Form';
import type { CreateAppointmentPayload, Location, Organization, Patient, PractitionerService, Practitioner, Room, OrganizationPractitioner } from '../../api/adminResources';

const schema = z.object({ organization_id: z.string().min(1), location_id: z.string().min(1), room_id: z.string().optional(), practitioner_id: z.string().min(1), practitioner_service_id: z.string().min(1), patient_id: z.string().min(1), date: z.string().min(1), starts_time: z.string().min(1), ends_time: z.string().min(1), notes: z.string().optional() }).refine((v) => `${v.date}T${v.starts_time}` < `${v.date}T${v.ends_time}`, { path: ['ends_time'], message: 'La hora fin debe ser posterior' });
type FormValues = z.infer<typeof schema>;
export function AppointmentForm({ selectedDate, organizations, locations, rooms, practitioners, relations, services, patients, isPending, onCancel, onSubmit }: { selectedDate: string; organizations: Organization[]; locations: Location[]; rooms: Room[]; practitioners: Practitioner[]; relations: OrganizationPractitioner[]; services: PractitionerService[]; patients: Patient[]; isPending?: boolean; onCancel?: () => void; onSubmit: (payload: CreateAppointmentPayload) => void }) {
  const form = useForm<FormValues>({ resolver: zodResolver(schema), defaultValues: { organization_id: '', location_id: '', room_id: '', practitioner_id: '', practitioner_service_id: '', patient_id: '', date: selectedDate, starts_time: '09:00', ends_time: '09:30', notes: '' } });
  useEffect(() => { form.setValue('date', selectedDate); }, [selectedDate, form]);
  const orgId = form.watch('organization_id'); const locId = form.watch('location_id'); const practitionerId = form.watch('practitioner_id'); const serviceId = form.watch('practitioner_service_id');
  const filteredLocations = locations.filter((l) => l.status === 'active' && (!orgId || l.organization_id === orgId));
  const filteredRooms = rooms.filter((r) => r.status === 'active' && (!locId || r.location_id === locId));
  const activePractitionerIds = new Set(relations.filter((r) => r.status === 'active' && r.organization_id === orgId).map((r) => r.practitioner_id));
  const filteredPractitioners = practitioners.filter((p) => p.status === 'active' && (!orgId || activePractitionerIds.has(p.id)));
  const filteredServices = services.filter((s) => s.status === 'active' && (!orgId || s.organization_id === orgId) && (!practitionerId || s.practitioner_id === practitionerId));
  const selectedService = useMemo(() => services.find((s) => s.id === serviceId), [services, serviceId]);
  useEffect(() => { if (selectedService) { const [h, m] = form.getValues('starts_time').split(':').map(Number); const d = new Date(Date.UTC(2026, 0, 1, h, m)); d.setUTCMinutes(d.getUTCMinutes() + selectedService.duration_minutes); form.setValue('ends_time', `${String(d.getUTCHours()).padStart(2, '0')}:${String(d.getUTCMinutes()).padStart(2, '0')}`); } }, [selectedService, form]);
  return <form className="grid gap-4 md:grid-cols-3" onSubmit={form.handleSubmit((v) => onSubmit({ organization_id: v.organization_id, location_id: v.location_id, room_id: v.room_id || null, practitioner_id: v.practitioner_id, practitioner_service_id: v.practitioner_service_id, patient_id: v.patient_id, starts_at: `${v.date}T${v.starts_time}:00`, ends_at: `${v.date}T${v.ends_time}:00`, notes: v.notes || null }))}><FieldWrapper label="Organización *"><Select {...form.register('organization_id')}><option value="">Selecciona</option>{organizations.filter((o) => o.status === 'active').map((o) => <option key={o.id} value={o.id}>{o.name}</option>)}</Select></FieldWrapper><FieldWrapper label="Sede *"><Select {...form.register('location_id')}><option value="">Selecciona</option>{filteredLocations.map((l) => <option key={l.id} value={l.id}>{l.name}</option>)}</Select></FieldWrapper><FieldWrapper label="Consultorio"><Select {...form.register('room_id')}><option value="">Sin consultorio</option>{filteredRooms.map((r) => <option key={r.id} value={r.id}>{r.name}</option>)}</Select></FieldWrapper><FieldWrapper label="Profesional *"><Select {...form.register('practitioner_id')}><option value="">Selecciona</option>{filteredPractitioners.map((p) => <option key={p.id} value={p.id}>{p.full_name}</option>)}</Select></FieldWrapper><FieldWrapper label="Servicio *"><Select {...form.register('practitioner_service_id')}><option value="">Selecciona</option>{filteredServices.map((s) => <option key={s.id} value={s.id}>{s.name} · {s.duration_minutes} min</option>)}</Select></FieldWrapper><FieldWrapper label="Paciente *"><Select {...form.register('patient_id')}><option value="">{patients.length ? 'Selecciona' : 'No hay pacientes disponibles'}</option>{patients.map((p) => <option key={p.id} value={p.id}>{[p.full_name, p.document_number, p.phone].filter(Boolean).join(' · ')}</option>)}</Select></FieldWrapper><FieldWrapper label="Fecha *"><Input type="date" {...form.register('date')} /></FieldWrapper><FieldWrapper label="Hora inicio *"><Input type="time" {...form.register('starts_time')} /></FieldWrapper><FieldWrapper label="Hora fin *" error={form.formState.errors.ends_time?.message}><Input type="time" {...form.register('ends_time')} /></FieldWrapper><FieldWrapper label="Notas"><Input {...form.register('notes')} /></FieldWrapper><div className="flex gap-2 md:col-span-3"><Button type="submit" disabled={isPending}>{isPending ? 'Creando…' : 'Crear cita'}</Button>{onCancel ? <Button type="button" variant="secondary" onClick={onCancel}>Cancelar</Button> : null}</div></form>;
}
