import { Badge } from '../../components/ui/Badge';
import { Button } from '../../components/ui/Button';
import { EmptyState } from '../../components/ui/States';
import type { AvailabilityException, Appointment, PractitionerAvailabilityRule } from '../../api/adminResources';
import { activeAgendaAvailabilityRules, buildAgendaItems, formatTimeRange } from './appointmentUtils';

export function AppointmentDailyAgenda({ selectedDate, practitionerId, serviceId, slotMinutes, rules, appointments, blocks, onEditAppointment, onAvailableSlot }: { selectedDate: string; practitionerId: string; serviceId?: string; slotMinutes: number; rules: PractitionerAvailabilityRule[]; appointments: Appointment[]; blocks: AvailabilityException[]; onEditAppointment: (a: Appointment) => void; onAvailableSlot?: (startsAt: string, endsAt: string) => void }) {
  if (!practitionerId) return <EmptyState title="Selecciona un profesional" description="Selecciona un profesional para ver espacios disponibles de agenda. Las citas y bloqueos existentes se mantienen en el listado administrativo." />;
  const activeRules = activeAgendaAvailabilityRules({ selectedDate, practitionerId, serviceId, rules });
  const events = buildAgendaItems({ selectedDate, practitionerId, serviceId, slotMinutes, rules, appointments, blocks });
  if (activeRules.length === 0) return <EmptyState title="Sin disponibilidad base" description="No hay disponibilidad base configurada para este profesional en el día seleccionado." />;
  if (events.length === 0) return <EmptyState title="Sin eventos" description={`No hay citas, bloqueos ni espacios generados para ${selectedDate}.`} />;
  return <div className="space-y-2">{events.map((e) => { const a = e.appointment; const b = e.block; return <article key={e.id} className={`rounded-xl border px-3 py-2 ${e.kind === 'available' ? 'border-emerald-200 bg-emerald-50' : e.kind === 'block' ? 'border-amber-200 bg-amber-50' : 'border-brand-100 bg-white'}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-sm font-bold text-slate-950">{formatTimeRange(e.starts_at, e.ends_at)}</p>{a ? e.isContinuation ? <><p className="font-semibold text-slate-900">Continuación de cita</p><p className="text-sm text-slate-600">{a.patient_name ?? 'Paciente'} · {a.practitioner_service_name ?? 'Servicio'}</p></> : <><p className="font-semibold text-slate-900">{a.patient_name ?? 'Paciente'}</p><p className="text-sm text-slate-600">{[a.practitioner_name, a.practitioner_service_name].filter(Boolean).join(' · ')}</p><p className="text-xs text-slate-500">{a.modality === 'virtual' ? [a.location_name, `Cita virtual · link ${a.virtual_link_status}`].filter(Boolean).join(' · ') : [a.location_name, a.room_name].filter(Boolean).join(' · ')}</p></> : b ? <><p className="font-semibold text-slate-900">{b.practitioner_name ?? 'Profesional'}</p><p className="text-sm text-slate-600">{b.exception_type_label}</p>{b.reason ? <p className="text-xs text-slate-500">Notas: {b.reason}</p> : null}<p className="text-xs text-slate-500">{[b.location_name, b.room_name].filter(Boolean).join(' · ') || 'General'}</p></> : <p className="text-sm text-emerald-800">Espacio disponible</p>}</div><div className="flex shrink-0 items-center gap-2"><Badge tone={e.kind === 'available' ? 'success' : e.kind === 'block' ? 'warning' : 'info'}>{e.kind === 'available' ? 'Disponible' : e.kind === 'block' ? 'Bloqueado' : a?.status_label ?? 'Ocupado'}</Badge>{a ? <Button variant="secondary" onClick={() => onEditAppointment(a)}>Editar</Button> : e.kind === 'available' && onAvailableSlot ? <Button variant="secondary" onClick={() => onAvailableSlot(e.starts_at, e.ends_at)}>Nueva cita</Button> : null}</div></div></article>; })}</div>;
}
